cameras:
  - name: "Office"
    source: "rtsp://user:password@192.168.0.101/stream"
  - name: "Lobby"
    source: "rtsp://user:password@192.168.0.102/stream"

settings:
  recording_path: "./recordings"
  log_path: "./logs/events.log"
